-- SQL запрос для вставки данных в creature_template_wdb_locale
-- Сгенерировано из Wowhead парсера
-- Локаль: ruRU
-- Всего NPC: 100
-- Успешно спарсено: 100

-- Удаляем существующие записи для всех ID
DELETE FROM `creature_template_wdb_locale` WHERE `Locale` = 'ruRU' AND `ID` IN (1,6,19,25,29,30,31,36,38,40,43,46,48,49,54,55,60,61,62,65,66,67,68,69,70,71,72,73,74,75,78,79,80,81,82,87,90,92,93,94,95,97,98,99,100,102,103,105,106,107,108,109,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,138,149,150,151,152,153,154,157,161,163,165,167,171,190,192,193,196,197,198,199,200,201,202,203,204,205,206,207);

-- Вставляем новые записи
INSERT INTO `creature_template_wdb_locale` (`ID`, `Locale`, `Name1`, `NameAlt1`, `Title`, `TitleAlt`) VALUES
(1, 'ruRU', 'Waypoint (Only GM can see it)', NULL, NULL, NULL),
(6, 'ruRU', 'Кобольд-вредитель', NULL, NULL, NULL),
(19, 'ruRU', 'Benny Questgiver', NULL, 'NPC', NULL),
(25, 'ruRU', 'NPC', NULL, NULL, NULL),
(29, 'ruRU', 'Канретад', NULL, 'Повелитель смерти', NULL),
(30, 'ruRU', 'Лесной паук', NULL, NULL, NULL),
(31, 'ruRU', 'Фурболг', NULL, NULL, NULL),
(36, 'ruRU', 'Уборочный голем', NULL, NULL, NULL),
(38, 'ruRU', 'Никудышный шаромыжник', NULL, NULL, NULL),
(40, 'ruRU', 'Кобольд-шахтер', NULL, NULL, NULL),
(43, 'ruRU', 'Рудниковый паук', NULL, NULL, NULL),
(46, 'ruRU', 'Мурлок-добытчик', NULL, NULL, NULL),
(48, 'ruRU', 'Скелет-воин', NULL, NULL, NULL),
(49, 'ruRU', 'Младший суккуб', NULL, NULL, NULL),
(54, 'ruRU', 'Корина Сталль', NULL, 'Оружейница', NULL),
(55, 'ruRU', 'Вредный Эд-Кузнец', NULL, NULL, NULL),
(60, 'ruRU', 'Руклар Зверолов', NULL, NULL, NULL),
(61, 'ruRU', 'Турос Ловкорук', NULL, NULL, NULL),
(62, 'ruRU', 'Гуг Толстая Свеча', NULL, NULL, NULL),
(65, 'ruRU', 'Крестьянка', NULL, NULL, NULL),
(66, 'ruRU', 'Таринн Боуден', NULL, 'Хозяйственные товары', NULL),
(67, 'ruRU', '[UNUSED] Marlon Darnik', NULL, 'Бакалейщик', NULL),
(68, 'ruRU', 'Штормградский стражник', NULL, NULL, NULL),
(69, 'ruRU', 'Больной лесной волк', NULL, NULL, NULL),
(70, 'ruRU', '[UNUSED] Lower Class Citizen', NULL, NULL, NULL),
(71, 'ruRU', 'Рангист', NULL, NULL, NULL),
(72, 'ruRU', 'Level 20 Unkillable Test Dummy', NULL, NULL, NULL),
(73, 'ruRU', 'Верейна-аптекарь', NULL, 'Задания', NULL),
(74, 'ruRU', 'Курран Сталль', NULL, 'Торговец тканевыми и кожаными доспехами', NULL),
(75, 'ruRU', '[UNUSED] Vashaum Nightwither', NULL, NULL, NULL),
(78, 'ruRU', 'Янош Камнекост', NULL, 'Оружейник', NULL),
(79, 'ruRU', 'Нарг Надсмотрщик', NULL, NULL, NULL),
(80, 'ruRU', 'Кобольд-рудокоп', NULL, NULL, NULL),
(81, 'ruRU', 'Праздник – Тыквовин – гарнизон – призрачный хмелементаль', NULL, NULL, NULL),
(82, 'ruRU', 'Безумный Леонетти', NULL, NULL, NULL),
(87, 'ruRU', 'Лесной тролль-берсерк', NULL, NULL, NULL),
(90, 'ruRU', 'Морской великан', NULL, NULL, NULL),
(92, 'ruRU', 'Каменный элементаль', NULL, NULL, NULL),
(93, 'ruRU', 'Кентавр', NULL, NULL, NULL),
(94, 'ruRU', 'Карманник', NULL, NULL, NULL),
(95, 'ruRU', 'Контрабандист из братства Справедливости', NULL, NULL, NULL),
(97, 'ruRU', 'Недоросток из стаи Речной Лапы', NULL, NULL, NULL),
(98, 'ruRU', 'Надсмотрщик из стаи Речной Лапы', NULL, NULL, NULL),
(99, 'ruRU', 'Моргана Лукавая', NULL, NULL, NULL),
(100, 'ruRU', 'Графф Быстрохват', NULL, NULL, NULL),
(102, 'ruRU', 'Бронзовый драконоид', NULL, NULL, NULL),
(103, 'ruRU', 'Гаррик Тихокрад', NULL, NULL, NULL),
(105, 'ruRU', 'Долгоног', NULL, NULL, NULL),
(106, 'ruRU', 'Кодо', NULL, NULL, NULL),
(107, 'ruRU', 'Ящер', NULL, NULL, NULL),
(108, 'ruRU', 'Зеленый драконоид', NULL, NULL, NULL),
(109, 'ruRU', 'Белый драконоид', NULL, NULL, NULL),
(111, 'ruRU', 'Жрец', NULL, NULL, NULL),
(112, 'ruRU', 'Жрица', NULL, NULL, NULL),
(113, 'ruRU', 'Вепрь-камнеклык', NULL, NULL, NULL),
(114, 'ruRU', 'Дозорный полей', NULL, NULL, NULL),
(115, 'ruRU', 'Уборочный голем', NULL, NULL, NULL),
(116, 'ruRU', 'Бандит', NULL, NULL, NULL),
(117, 'ruRU', 'Гнолл из стаи Речной Лапы', NULL, NULL, NULL),
(118, 'ruRU', 'Лесной хищник', NULL, NULL, NULL),
(119, 'ruRU', 'Длиннорыл', NULL, NULL, NULL),
(120, 'ruRU', 'Лесной паук-ловец', NULL, NULL, NULL),
(121, 'ruRU', 'Ищейка из братства Справедливости', NULL, NULL, NULL),
(122, 'ruRU', 'Проходимец из братства Справедливости', NULL, NULL, NULL),
(123, 'ruRU', 'Полукровка из стаи Речной Лапы', NULL, NULL, NULL),
(124, 'ruRU', 'Громила из стаи Речной Лапы', NULL, NULL, NULL),
(125, 'ruRU', 'Надзиратель из стаи Речной Лапы', NULL, NULL, NULL),
(126, 'ruRU', 'Мурлок-береговик', NULL, NULL, NULL),
(127, 'ruRU', 'Мурлок-волнолов', NULL, NULL, NULL),
(128, 'ruRU', 'Траляля разъяренного программиста', NULL, NULL, NULL),
(129, 'ruRU', 'Труляля разъяренного программиста', NULL, NULL, NULL),
(130, 'ruRU', 'Программист - торговец', NULL, NULL, NULL),
(138, 'ruRU', 'NPC', NULL, NULL, NULL),
(149, 'ruRU', '[UNUSED] Small Black Dragon Whelp', NULL, NULL, NULL),
(150, 'ruRU', '[UNUSED] Brother Milius', NULL, 'Торговец луками', NULL),
(151, 'ruRU', 'Брог Хэмфист', NULL, 'Сто мелочей', NULL),
(152, 'ruRU', 'Брат Даниль', NULL, 'Сто мелочей', NULL),
(153, 'ruRU', 'Бетина', NULL, 'Продавец маленьких мурлоков', NULL),
(154, 'ruRU', 'Большой шкуродер', NULL, NULL, NULL),
(157, 'ruRU', 'Кровоклык', NULL, NULL, NULL),
(161, 'ruRU', '[UNUSED] Ander the Monk', NULL, NULL, NULL),
(163, 'ruRU', '[UNUSED] Destitute Farmer', NULL, NULL, NULL),
(165, 'ruRU', '[UNUSED] Small Child', NULL, NULL, NULL),
(167, 'ruRU', 'Моран Медношпунт', NULL, 'Металлург', NULL),
(171, 'ruRU', 'Мурлок-воин', NULL, NULL, NULL),
(190, 'ruRU', 'Дермот Джонс', NULL, 'Торговец тканевыми и кожаными доспехами', NULL),
(192, 'ruRU', 'Ледяной тролль', NULL, NULL, NULL),
(193, 'ruRU', 'Синий драконоид', NULL, NULL, NULL),
(196, 'ruRU', 'Иган Меховщик', NULL, NULL, NULL),
(197, 'ruRU', 'Маршал Макбрайд', NULL, NULL, NULL),
(198, 'ruRU', 'Кельден Бремен', NULL, 'Наставник магов', NULL),
(199, 'ruRU', 'Молодой шкуродер', NULL, NULL, NULL),
(200, 'ruRU', 'Шаркающий скелет UNUSED', NULL, NULL, NULL),
(201, 'ruRU', 'Хрупкий скелет', NULL, NULL, NULL),
(202, 'ruRU', 'Гниющий ужас', NULL, NULL, NULL),
(203, 'ruRU', 'Маг-скелет', NULL, NULL, NULL),
(204, 'ruRU', '[UNUSED] Cackle Flamebone', NULL, NULL, NULL),
(205, 'ruRU', 'Вестник Тьмы из стаи Ночной Погибели', NULL, NULL, NULL),
(206, 'ruRU', 'Ярый Клык Ночной Погибели', NULL, NULL, NULL),
(207, 'ruRU', '[UNUSED] Riverpaw Hideflayer', NULL, NULL, NULL);

-- Всего записей для вставки: 100

-- SQL запрос для вставки данных в creature_template_wdb_locale
-- Сгенерировано из Wowhead парсера
-- Локаль: ruRU
-- Всего NPC: 100
-- Успешно спарсено: 100

-- Удаляем существующие записи для всех ID
DELETE FROM `creature_template_wdb_locale` WHERE `Locale` = 'ruRU' AND `ID` IN (208,209,210,211,212,213,215,217,218,219,220,221,222,223,224,225,226,227,228,229,230,232,233,234,235,237,238,239,240,241,242,243,244,246,247,248,250,251,252,253,255,257,258,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,294,295,296,297,298,299,300,301,302,303,306,307,308,309,311,313,314,315,318,319,320,321,322,323,324);

-- Вставляем новые записи
INSERT INTO `creature_template_wdb_locale` (`ID`, `Locale`, `Name1`, `NameAlt1`, `Title`, `TitleAlt`) VALUES
(208, 'ruRU', '[UNUSED] Riverpaw Pack Warder', NULL, NULL, NULL),
(209, 'ruRU', '[UNUSED] Riverpaw Bone Chanter', NULL, NULL, NULL),
(210, 'ruRU', 'Костеглод', NULL, NULL, NULL),
(211, 'ruRU', 'Огр', NULL, NULL, NULL),
(212, 'ruRU', 'Воин из клана Дробящего Кулака', NULL, NULL, NULL),
(213, 'ruRU', 'Голодный лютый волк', NULL, NULL, NULL),
(215, 'ruRU', 'Ночной гонец из братства Справедливости', NULL, NULL, NULL),
(217, 'ruRU', 'Ядовитый кругопряд', NULL, NULL, NULL),
(218, 'ruRU', 'Расхититель могил', NULL, NULL, NULL),
(219, 'ruRU', '[UNUSED] Logan Mar', NULL, 'Торговец тканевыми и кожаными доспехами', NULL),
(220, 'ruRU', '[UNUSED] Khebil Steelsmith', NULL, 'Оружейник', NULL),
(221, 'ruRU', 'Даннас', NULL, 'Торговец', NULL),
(222, 'ruRU', 'Нилиен Аденмар', NULL, 'Кователь булав', NULL),
(223, 'ruRU', 'Дэн Голтас', NULL, 'Ученик кожевника', NULL),
(224, 'ruRU', 'Зок Марстон', NULL, 'Продавец оружия', NULL),
(225, 'ruRU', 'Гавин Гнутодрев', NULL, 'Оружейник', NULL),
(226, 'ruRU', 'Морг Гнутодрев', NULL, 'Бронник', NULL),
(227, 'ruRU', 'Мейбл Солаж', NULL, 'Потребительские товары', NULL),
(228, 'ruRU', 'Аветта Хвористинка', NULL, 'Торговка луками', NULL),
(229, 'ruRU', 'Unknown Evil Transform (do not translate)', NULL, NULL, NULL),
(230, 'ruRU', 'Торнтон Хвористинка', NULL, 'Плотник', NULL),
(232, 'ruRU', 'Фермер Рей', NULL, NULL, NULL),
(233, 'ruRU', 'Фермер Сальден', NULL, NULL, NULL),
(234, 'ruRU', 'Маршал Гриан Камнегрив', NULL, 'Дружина Западного края', NULL),
(235, 'ruRU', 'Сальма Сальден', NULL, NULL, NULL),
(237, 'ruRU', 'Фермер Хмуробров', NULL, NULL, NULL),
(238, 'ruRU', 'Верна Хмуробров', NULL, NULL, NULL),
(239, 'ruRU', 'Мрачнобух Громовар', NULL, NULL, NULL),
(240, 'ruRU', 'Маршал Дугхан', NULL, NULL, NULL),
(241, 'ruRU', 'Реми Повторюх', NULL, NULL, NULL),
(242, 'ruRU', 'Хоррас Браквелл', NULL, NULL, NULL),
(243, 'ruRU', '[UNUSED] Greeby Mudwhisker TEST', NULL, NULL, NULL),
(244, 'ruRU', 'Мамаша Стоунфилд', NULL, NULL, NULL),
(246, 'ruRU', '"Тетушка" Бернис Стоунфилд', NULL, NULL, NULL),
(247, 'ruRU', 'Билли Маклур', NULL, NULL, NULL),
(248, 'ruRU', 'Бабуля Стоунфилд', NULL, NULL, NULL),
(250, 'ruRU', 'Папаша Маклур', NULL, NULL, NULL),
(251, 'ruRU', 'Мейбелл Маклур', NULL, NULL, NULL),
(252, 'ruRU', 'Томми Джо Стоунфилд', NULL, NULL, NULL),
(253, 'ruRU', 'Вильям Пест', NULL, NULL, NULL),
(255, 'ruRU', 'Джерард Румпель', NULL, NULL, NULL),
(257, 'ruRU', 'Кобольд-рабочий', NULL, NULL, NULL),
(258, 'ruRU', 'Джошуа Маклур', NULL, 'Виноторговец', NULL),
(260, 'ruRU', '[UNUSED] Elwynn Tower Guard', NULL, NULL, NULL),
(261, 'ruRU', 'Стражник Томас', NULL, NULL, NULL),
(262, 'ruRU', '[DND] Wounded Lion''s Footman', NULL, NULL, NULL),
(263, 'ruRU', 'Лорд Элло Чернодрев', NULL, 'Мэр Темнолесья', NULL),
(264, 'ruRU', 'Командир Алтея Чернодрев', NULL, 'Глава Ночного дозора', NULL),
(265, 'ruRU', 'Мадам Ева', NULL, NULL, NULL),
(266, 'ruRU', 'Вилли Черный', NULL, NULL, NULL),
(267, 'ruRU', 'Клерк Далтри', NULL, NULL, NULL),
(268, 'ruRU', 'Шира Фон-Инди', NULL, 'Историк Темнолесья', NULL),
(269, 'ruRU', 'Роул Дрейгер', NULL, 'Вице-мэр Темнолесья', NULL),
(270, 'ruRU', 'Член совета Миллстайп', NULL, 'Городской совет Темнолесья', NULL),
(271, 'ruRU', 'Посол Беррибак', NULL, 'Городской совет Темнолесья', NULL),
(272, 'ruRU', 'Шеф-повар Груаль', NULL, NULL, NULL),
(273, 'ruRU', 'Хозяин таверны Смиттс', NULL, NULL, NULL),
(274, 'ruRU', 'Кабатчик Ханн', NULL, 'Бармен', NULL),
(275, 'ruRU', 'Бел Вонтмал', NULL, NULL, NULL),
(276, 'ruRU', 'Виктор Призм''Антрас', NULL, NULL, NULL),
(277, 'ruRU', 'Роберто Пуплливербос', NULL, 'Знаток вин', NULL),
(278, 'ruRU', 'Сара Тимберлейн', NULL, NULL, NULL),
(279, 'ruRU', 'Морган Пест', NULL, NULL, NULL),
(280, 'ruRU', 'Placeholder - Jasperlode Mine', NULL, 'Area Trigger', NULL),
(281, 'ruRU', 'Кобольд-танк', NULL, NULL, NULL),
(282, 'ruRU', 'Кобольд-заклинатель', NULL, NULL, NULL),
(283, 'ruRU', 'Кобольд-целитель', NULL, NULL, NULL),
(284, 'ruRU', 'Гнедой конь', NULL, NULL, NULL),
(285, 'ruRU', 'Мурлок', NULL, NULL, NULL),
(286, 'ruRU', 'Старый Гниложабр', NULL, NULL, NULL),
(287, 'ruRU', 'Приказчик - шахта Черная дыра', NULL, NULL, NULL),
(288, 'ruRU', 'Трясунчик', NULL, NULL, NULL),
(289, 'ruRU', 'Аберкромби', NULL, 'Отшельник', NULL),
(290, 'ruRU', 'Placeholder - Fargodeep Mine', NULL, 'Area Trigger', NULL),
(291, 'ruRU', 'Placeholder Chest of Drawers', NULL, 'Placeholder!', NULL),
(294, 'ruRU', 'Маршал Хаггард', NULL, NULL, NULL),
(295, 'ruRU', 'Фарли', NULL, 'Хозяин таверны', NULL),
(296, 'ruRU', '[UNUSED] Goodmother Jans', NULL, NULL, NULL),
(297, 'ruRU', 'Управляющий Фольсом', NULL, NULL, NULL),
(298, 'ruRU', '[UNUSED] Aunt Bethda <<Текстура отсутствует>>', NULL, NULL, NULL),
(299, 'ruRU', 'Молодой волк', NULL, NULL, NULL),
(300, 'ruRU', 'Ззарк''Вул', NULL, NULL, NULL),
(301, 'ruRU', '[UNUSED] Brog''Mud', NULL, NULL, NULL),
(302, 'ruRU', 'Слепая Мэри', NULL, NULL, NULL),
(303, 'ruRU', 'Placeholder Interactive Doodad - jk', NULL, 'Проявите фантазию', NULL),
(306, 'ruRU', 'Игреневый конь', NULL, NULL, NULL),
(307, 'ruRU', 'Пегий конь', NULL, NULL, NULL),
(308, 'ruRU', 'Вороной жеребец', NULL, NULL, NULL),
(309, 'ruRU', '"Buried Upside-Down" Vehicle', NULL, NULL, NULL),
(311, 'ruRU', 'Свен Йорген', NULL, NULL, NULL),
(313, 'ruRU', 'Теокрит', NULL, 'Маг башни Азоры', NULL),
(314, 'ruRU', 'Элиза', NULL, 'Невеста Бальзамировщика', NULL),
(315, 'ruRU', 'Сталван Мистмантл', NULL, NULL, NULL),
(318, 'ruRU', '[UNUSED] Brother Akil', NULL, NULL, NULL),
(319, 'ruRU', '[UNUSED] Brother Benthas', NULL, NULL, NULL),
(320, 'ruRU', '[UNUSED] Brother Cryus', NULL, NULL, NULL),
(321, 'ruRU', '[UNUSED] Brother Deros', NULL, NULL, NULL),
(322, 'ruRU', '[UNUSED] Brother Enoch', NULL, NULL, NULL),
(323, 'ruRU', '[UNUSED] Brother Farthing', NULL, NULL, NULL),
(324, 'ruRU', '[UNUSED] Brother Greishan', NULL, NULL, NULL);

-- Всего записей для вставки: 100


-- SQL запрос для вставки данных в creature_template_wdb_locale
-- Сгенерировано из Wowhead парсера
-- Локаль: ruRU
-- Всего NPC: 300
-- Успешно спарсено: 299

-- Удаляем существующие записи для всех ID
DELETE FROM `creature_template_wdb_locale` WHERE `Locale` = 'ruRU' AND `ID` IN (325,326,327,328,329,330,331,332,333,334,335,336,338,339,340,341,342,343,344,345,346,347,348,349,351,352,353,354,356,357,358,359,361,364,365,370,371,372,373,374,375,376,377,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,395,397,399,400,401,402,403,404,405,406,407,408,409,410,411,412,415,418,421,422,423,424,426,428,429,430,431,432,433,434,435,436,437,440,441,442,445,446,448,449,450,452,453,454,456,458,459,460,461,462,464,465,466,467,468,469,470,471,472,473,474,475,476,478,480,481,482,483,485,486,487,488,489,490,491,494,495,496,497,498,499,500,501,502,503,504,505,506,507,509,510,511,513,514,515,516,517,518,519,520,521,522,523,524,525,531,533,534,535,536,538,539,541,542,543,544,545,547,548,550,564,565,566,567,568,569,570,572,573,574,575,576,578,579,580,582,583,584,586,587,588,589,590,592,594,595,596,597,598,599,601,603,604,605,606,607,609,610,611,612,613,614,615,616,619,620,621,622,623,624,625,626,628,631,633,634,636,638,639,641,642,643,644,645,646,647,648,649,650,651,652,653,656,657,658,659,660,661,663,664,667,669,670,671,672,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,693,694,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712);

-- Вставляем новые записи
INSERT INTO `creature_template_wdb_locale` (`ID`, `Locale`, `Name1`, `NameAlt1`, `Title`, `TitleAlt`) VALUES
(325, 'ruRU', 'Хоган Ференс', NULL, NULL, NULL),
(326, 'ruRU', '[UNUSED] Brother Ictharin', NULL, NULL, NULL),
(327, 'ruRU', 'Фикс', NULL, NULL, NULL),
(328, 'ruRU', 'Залдимар Вефхеллт', NULL, 'Наставник магов', NULL),
(329, 'ruRU', 'Элементаль земли', NULL, NULL, NULL),
(330, 'ruRU', 'Принцесса', NULL, NULL, NULL),
(331, 'ruRU', 'Магинор Дюма', NULL, 'Магистр магии', NULL),
(332, 'ruRU', 'Мастер Матиас Шоу', NULL, 'Глава ШРУ', NULL),
(333, 'ruRU', '[UNUSED] Edwardo the Jester', NULL, NULL, NULL),
(334, 'ruRU', 'Гат''Илзогг', NULL, 'Вождь клана Черной горы', NULL),
(335, 'ruRU', 'Обжигайка', NULL, NULL, NULL),
(336, 'ruRU', '[UNUSED] Rin Tal''Vara', NULL, NULL, NULL),
(338, 'ruRU', 'Мазен Макнадир', NULL, 'Академия волшебных наук и искусств', NULL),
(339, 'ruRU', '[UNUSED] Helgor the Pugilist', NULL, NULL, NULL),
(340, 'ruRU', 'Кендор Кабонка', NULL, 'Знаток кулинарных рецептов', NULL),
(341, 'ruRU', 'Штейгер Ослоу', NULL, NULL, NULL),
(342, 'ruRU', 'Марти Джанроз', NULL, NULL, NULL),
(343, 'ruRU', 'Шеф-повар Брианна', NULL, NULL, NULL),
(344, 'ruRU', 'Мировой судья Соломон', NULL, NULL, NULL),
(345, 'ruRU', 'Грубобрюх', NULL, NULL, NULL),
(346, 'ruRU', 'Кабатчик Дэниэлс', NULL, NULL, NULL),
(347, 'ruRU', 'Седынь Полушкур', NULL, 'Военачальник Альтеракской долины', NULL),
(348, 'ruRU', 'Зем Ливард', NULL, NULL, NULL),
(349, 'ruRU', 'Капрал Кишан', NULL, NULL, NULL),
(351, 'ruRU', 'Крестьянин', NULL, NULL, NULL),
(352, 'ruRU', 'Дунгар Долгопив', NULL, 'Укротитель грифонов', NULL),
(353, 'ruRU', 'Антония Дарт', NULL, 'Продавец маленьких мурлоков', NULL),
(354, 'ruRU', '[UNUSED] Grall Twomoons', NULL, 'Наставник шаманов', NULL),
(356, 'ruRU', 'Черный волк', NULL, NULL, NULL),
(357, 'ruRU', 'NPC MoP', NULL, NULL, NULL),
(358, 'ruRU', 'Лесной волк', NULL, NULL, NULL),
(359, 'ruRU', 'Снежный волк', NULL, NULL, NULL),
(361, 'ruRU', 'Сайтр', NULL, NULL, NULL),
(364, 'ruRU', 'Слизь', NULL, NULL, NULL),
(365, 'ruRU', 'Scott''s Flying Mount', NULL, NULL, NULL),
(370, 'ruRU', 'Мальчик', NULL, NULL, NULL),
(371, 'ruRU', 'Девочка', NULL, NULL, NULL),
(372, 'ruRU', 'Карм Железное Перо', NULL, 'Товары для горного дела', NULL),
(373, 'ruRU', 'Марак Дитя Зимы', NULL, 'Наставник шаманов', NULL),
(374, 'ruRU', 'Зубец Светоблеск', NULL, NULL, NULL),
(375, 'ruRU', 'Жрица Анетта', NULL, 'Наставница жрецов', NULL),
(376, 'ruRU', 'Верховная жрица Лорена', NULL, 'Наставница жрецов', NULL),
(377, 'ruRU', 'Жрица Жозетта', NULL, 'Наставница жрецов', NULL),
(379, 'ruRU', 'Дарси Паркер', NULL, NULL, NULL),
(380, 'ruRU', '[UNUSED] Waldin Thorbatt', NULL, NULL, NULL),
(381, 'ruRU', 'Начальник дока Барен', NULL, NULL, NULL),
(382, 'ruRU', 'Маршал Маррис', NULL, NULL, NULL),
(383, 'ruRU', 'Джейсон Матерс', NULL, 'Торговец рыбой и снастями', NULL),
(384, 'ruRU', 'Кати Охотница', NULL, 'Конезаводчица', NULL),
(385, 'ruRU', 'Лошадь', NULL, NULL, NULL),
(386, 'ruRU', '[UNUSED] Ulric the Grim', NULL, 'Торговец волками', NULL),
(387, 'ruRU', 'Лорд Самуэль', NULL, 'Магистр-паладин', NULL),
(388, 'ruRU', 'Бромос Мерфи', NULL, 'Магистр-паладин', NULL),
(389, 'ruRU', 'Лорд Лантинга', NULL, 'Магистр-паладин', NULL),
(390, 'ruRU', 'Кабан из свиты', NULL, NULL, NULL),
(391, 'ruRU', 'Старый Мрачноглаз', NULL, NULL, NULL),
(392, 'ruRU', 'Капитан Грейсон', NULL, NULL, NULL),
(393, 'ruRU', 'Ручной волк', NULL, NULL, NULL),
(395, 'ruRU', 'Марк', NULL, NULL, NULL),
(397, 'ruRU', 'Великий волхв Доан', NULL, NULL, NULL),
(399, 'ruRU', 'Boy - placeholder 05', NULL, NULL, NULL),
(400, 'ruRU', 'Boy - placeholder 06', NULL, NULL, NULL),
(401, 'ruRU', 'Boy - placeholder 07', NULL, NULL, NULL),
(402, 'ruRU', 'Boy - placeholder 08', NULL, NULL, NULL),
(403, 'ruRU', 'Boy - placeholder 09', NULL, NULL, NULL),
(404, 'ruRU', 'Girl - placeholder 01', NULL, NULL, NULL),
(405, 'ruRU', 'Girl - placeholder 02', NULL, NULL, NULL),
(406, 'ruRU', 'Girl - placeholder 03', NULL, NULL, NULL),
(407, 'ruRU', 'Girl - placeholder 04', NULL, NULL, NULL),
(408, 'ruRU', 'Girl - placeholder 05', NULL, NULL, NULL),
(409, 'ruRU', 'Girl - placeholder 06', NULL, NULL, NULL),
(410, 'ruRU', 'Girl - placeholder 07', NULL, NULL, NULL),
(411, 'ruRU', 'Girl - placeholder 08', NULL, NULL, NULL),
(412, 'ruRU', 'Стежок', NULL, 'Подарок Бальзамировщика', NULL),
(415, 'ruRU', 'Вернер Осгуд', NULL, NULL, NULL),
(418, 'ruRU', 'Малый демон Бездны', NULL, NULL, NULL),
(421, 'ruRU', 'Морфест', NULL, NULL, NULL),
(422, 'ruRU', 'Мурлок-трупоед', NULL, NULL, NULL),
(423, 'ruRU', 'Полукровка из стаи Красногорья', NULL, NULL, NULL),
(424, 'ruRU', 'Браконьер из стаи Красногорья', NULL, NULL, NULL),
(426, 'ruRU', 'Громила из стаи Красногорья', NULL, NULL, NULL),
(428, 'ruRU', 'Ужасающий кондор', NULL, NULL, NULL),
(429, 'ruRU', 'Темноплет из стаи Темношкуров', NULL, NULL, NULL),
(430, 'ruRU', 'Мистик из стаи Красногорья', NULL, NULL, NULL),
(431, 'ruRU', 'Душегуб из стаи Темношкуров', NULL, NULL, NULL),
(432, 'ruRU', 'Громила из стаи Темношкуров', NULL, NULL, NULL),
(433, 'ruRU', 'Гнолл из стаи Темношкуров', NULL, NULL, NULL),
(434, 'ruRU', 'Бешеный гнолл из стаи Темношкуров', NULL, NULL, NULL),
(435, 'ruRU', 'Воитель из клана Черной горы', NULL, NULL, NULL),
(436, 'ruRU', 'Темный чародей из клана Черной горы', NULL, NULL, NULL),
(437, 'ruRU', 'Перебежчик из клана Черной горы', NULL, NULL, NULL),
(440, 'ruRU', 'Рубака из клана Черной горы', NULL, NULL, NULL),
(441, 'ruRU', 'Черный дракончик', NULL, NULL, NULL),
(442, 'ruRU', 'Тарантул', NULL, NULL, NULL),
(445, 'ruRU', 'Вожак стаи Красногорья', NULL, NULL, NULL),
(446, 'ruRU', 'Губитель из стаи Красногорья', NULL, NULL, NULL),
(448, 'ruRU', 'Дробитель', NULL, NULL, NULL),
(449, 'ruRU', 'Кастетник из Братства Справедливости', NULL, NULL, NULL),
(450, 'ruRU', 'Маг-отступник из Братства Справедливости', NULL, NULL, NULL),
(452, 'ruRU', 'Бандит из стаи Речной Лапы', NULL, NULL, NULL),
(453, 'ruRU', 'Мистик из стаи Речной Лапы', NULL, NULL, NULL),
(454, 'ruRU', 'Молодой кровоклык', NULL, NULL, NULL),
(456, 'ruRU', 'Низший мурлок-оракул', NULL, NULL, NULL),
(458, 'ruRU', 'Мурлок-охотник', NULL, NULL, NULL),
(459, 'ruRU', 'Друзилла ла Салле', NULL, 'Наставница чернокнижников', NULL),
(460, 'ruRU', 'Аламар Мрачнн', NULL, 'Наставник чернокнижников', NULL),
(461, 'ruRU', 'Демизетта Клойс', NULL, 'Наставница чернокнижников', NULL),
(462, 'ruRU', 'Сарыч', NULL, NULL, NULL),
(464, 'ruRU', 'Капитан стражи Паркер', NULL, NULL, NULL),
(465, 'ruRU', 'Кабатчик Доббинз', NULL, 'Бармен', NULL),
(466, 'ruRU', 'Генерал Маркус Джонатан', NULL, 'Главнокомандующий гарнизоном Штормграда', NULL),
(467, 'ruRU', 'Предатель Братства Справедливости', NULL, NULL, NULL),
(468, 'ruRU', 'Городской глашатай', NULL, NULL, NULL),
(469, 'ruRU', 'Лейтенант Дорен', NULL, NULL, NULL),
(470, 'ruRU', '[UNUSED] Scribe Colburg', NULL, NULL, NULL),
(471, 'ruRU', 'Мать Клык', NULL, NULL, NULL),
(472, 'ruRU', 'Федфенхель', NULL, NULL, NULL),
(473, 'ruRU', 'Морган Вымогатель', NULL, NULL, NULL),
(474, 'ruRU', 'Плутоватый маг', NULL, NULL, NULL),
(475, 'ruRU', 'Кобольд-проходчик', NULL, NULL, NULL),
(476, 'ruRU', 'Кобольд-геомант', NULL, NULL, NULL),
(478, 'ruRU', 'Гонец из стаи Речной Лапы', NULL, NULL, NULL),
(480, 'ruRU', 'Ржавый уборочный голем', NULL, NULL, NULL),
(481, 'ruRU', 'Преступник из Братства Справедливости', NULL, NULL, NULL),
(482, 'ruRU', 'Иллинг Триас', NULL, 'Специалист по сыру', NULL),
(483, 'ruRU', 'Илана Триас', NULL, 'Специалистка по сыру', NULL),
(485, 'ruRU', 'Вестник из клана Черной горы', NULL, NULL, NULL),
(486, 'ruRU', 'Тарил''зун', NULL, NULL, NULL),
(487, 'ruRU', 'Заступник Биалон', NULL, 'Дружина Западного края', NULL),
(488, 'ruRU', 'Заступник Вивер', NULL, 'Дружина Западного края', NULL),
(489, 'ruRU', 'Заступник Датфилд', NULL, 'Дружина Западного края', NULL),
(490, 'ruRU', 'Заступник Гариэл', NULL, 'Дружина Западного края', NULL),
(491, 'ruRU', 'Интендант Льюис', NULL, 'Интендант', NULL),
(494, 'ruRU', 'Дозорный Бакурис', NULL, 'Ночной Дозор', NULL),
(495, 'ruRU', 'Дозорная Кифер', NULL, 'Ночной Дозор', NULL),
(496, 'ruRU', '[UNUSED] Watcher Kleeman', NULL, NULL, NULL),
(497, 'ruRU', '[UNUSED] Watcher Benjamin', NULL, NULL, NULL),
(498, 'ruRU', '[UNUSED] Watcher Larsen', NULL, NULL, NULL),
(499, 'ruRU', 'Дозорный Пейдж', NULL, 'Ночной Дозор', NULL),
(500, 'ruRU', 'Разведчик из стаи Речной Лапы', NULL, NULL, NULL),
(501, 'ruRU', 'Травник из стаи Речной Лапы', NULL, NULL, NULL),
(502, 'ruRU', 'Вит Карлеон', NULL, NULL, NULL),
(503, 'ruRU', 'Лорд Малатром', NULL, NULL, NULL),
(504, 'ruRU', 'Зверолов из Братства Справедливости', NULL, NULL, NULL),
(505, 'ruRU', 'Крупный тарантул', NULL, NULL, NULL),
(506, 'ruRU', 'Сержант Острый Коготь', NULL, NULL, NULL),
(507, 'ruRU', 'Фенрос', NULL, NULL, NULL),
(509, 'ruRU', '[UNUSED] Long Fang', NULL, NULL, NULL),
(510, 'ruRU', 'Элементаль воды', NULL, NULL, NULL),
(511, 'ruRU', 'Невменяемый вурдалак', NULL, NULL, NULL),
(513, 'ruRU', 'Мурлок-сетеплет', NULL, NULL, NULL),
(514, 'ruRU', 'Кузнец Аргус', NULL, 'Учитель кузнечного дела', NULL),
(515, 'ruRU', 'Мурлок-налетчик', NULL, NULL, NULL),
(516, 'ruRU', '[UNUSED] Riverpaw Hunter', NULL, NULL, NULL),
(517, 'ruRU', 'Мурлок-оракул', NULL, NULL, NULL),
(518, 'ruRU', 'Изувой', NULL, NULL, NULL),
(519, 'ruRU', 'Сларк', NULL, NULL, NULL),
(520, 'ruRU', 'Бракк', NULL, NULL, NULL),
(521, 'ruRU', 'Волкус', NULL, NULL, NULL),
(522, 'ruRU', 'Мор''Ладим', NULL, NULL, NULL),
(523, 'ruRU', 'Тор', NULL, 'Укротитель грифонов', NULL),
(524, 'ruRU', 'Камнешкурый вепрь', NULL, NULL, NULL),
(525, 'ruRU', 'Облезлый волк', NULL, NULL, NULL),
(531, 'ruRU', 'Скелет-губитель', NULL, NULL, NULL),
(533, 'ruRU', 'Маг теней из стаи Ночной Погибели', NULL, NULL, NULL),
(534, 'ruRU', 'Нефару', NULL, 'Мать логова', NULL),
(535, 'ruRU', '[UNUSED] Savar', NULL, NULL, NULL),
(536, 'ruRU', '[UNUSED] Rhal''Del', NULL, NULL, NULL),
(538, 'ruRU', '[UNUSED] Buk''Cha', NULL, NULL, NULL),
(539, 'ruRU', 'Карликовый ядовитый кругопряд', NULL, NULL, NULL),
(541, 'ruRU', 'Верховой грифон', NULL, NULL, NULL),
(542, 'ruRU', 'Калифекс из глубокого леса', NULL, 'Наставник друидов', NULL),
(543, 'ruRU', 'Налезетта Буйный Нрав', NULL, 'Смотритель стойл', NULL),
(544, 'ruRU', 'Мурлок-следопыт', NULL, NULL, NULL),
(545, 'ruRU', 'Мурлок-волномут', NULL, NULL, NULL),
(547, 'ruRU', 'Большой кровоклык', NULL, NULL, NULL),
(548, 'ruRU', 'Низший мурлок-волномут', NULL, NULL, NULL),
(550, 'ruRU', 'Вестник из Братства Справедливости', NULL, NULL, NULL),
(564, 'ruRU', 'Раб-кобольд', NULL, NULL, NULL),
(565, 'ruRU', 'Бешеный волк', NULL, NULL, NULL),
(566, 'ruRU', 'В''рекс', NULL, NULL, NULL),
(567, 'ruRU', 'Чернокоготь', NULL, NULL, NULL),
(568, 'ruRU', 'Воин из стаи Темношкуров', NULL, NULL, NULL),
(569, 'ruRU', 'Зеленый паук-отшельник', NULL, NULL, NULL),
(570, 'ruRU', 'Мозгоед', NULL, NULL, NULL),
(572, 'ruRU', 'Лепритус', NULL, NULL, NULL),
(573, 'ruRU', 'Врагорез-4000', NULL, NULL, NULL),
(574, 'ruRU', 'Нараксис', NULL, NULL, NULL),
(575, 'ruRU', 'Элементаль огня', NULL, NULL, NULL),
(576, 'ruRU', 'Дозорный Ладимор', NULL, 'Ночной Дозор', NULL),
(578, 'ruRU', 'Мурлок-разведчик', NULL, NULL, NULL),
(579, 'ruRU', 'Убийца из стаи Темношкуров', NULL, NULL, NULL),
(580, 'ruRU', 'Чернорабочий из стаи Красногорья', NULL, NULL, NULL),
(582, 'ruRU', 'Старая Савраска', NULL, NULL, NULL),
(583, 'ruRU', 'Душитель', NULL, NULL, NULL),
(584, 'ruRU', 'Казон', NULL, NULL, NULL),
(586, 'ruRU', '[UNUSED] Watcher Kern', NULL, NULL, NULL),
(587, 'ruRU', 'Воин из племени Кровавого Скальпа', NULL, NULL, NULL),
(588, 'ruRU', 'Разведчик из племени Кровавого Скальпа', NULL, NULL, NULL),
(589, 'ruRU', 'Погромщик из Братства Справедливости', NULL, NULL, NULL),
(590, 'ruRU', 'Мошенник из Братства Справедливости', NULL, NULL, NULL),
(592, 'ruRU', '[UNUSED] Defias Arsonist', NULL, NULL, NULL),
(594, 'ruRU', 'Подручный из Братства Справедливости', NULL, NULL, NULL),
(595, 'ruRU', 'Охотник из племени Кровавого Скальпа', NULL, NULL, NULL),
(596, 'ruRU', 'Зомбированный дворянин', NULL, NULL, NULL),
(597, 'ruRU', 'Берсерк из племени Кровавого Скальпа', NULL, NULL, NULL),
(598, 'ruRU', 'Шахтер из Братства Справедливости', NULL, NULL, NULL),
(599, 'ruRU', 'Мариса дю Пэж', NULL, NULL, NULL),
(601, 'ruRU', 'Жадный Капо', NULL, NULL, NULL),
(603, 'ruRU', 'Темнозуб', NULL, NULL, NULL),
(604, 'ruRU', 'Распространитель чумы', NULL, NULL, NULL),
(605, 'ruRU', '[UNUSED] Mr. Whipple', NULL, NULL, NULL),
(606, 'ruRU', '[UNUSED] Mrs. Whipple', NULL, NULL, NULL),
(607, 'ruRU', '[UNUSED] Johnny Whipple', NULL, NULL, NULL),
(609, 'ruRU', '[UNUSED] Grandpa Whipple', NULL, NULL, NULL),
(610, 'ruRU', '[UNUSED] Rabid Gina Whipple', NULL, NULL, NULL),
(611, 'ruRU', '[UNUSED] Rabid Mr. Whipple', NULL, NULL, NULL),
(612, 'ruRU', '[UNUSED] Rabid Mrs. Whipple', NULL, NULL, NULL),
(613, 'ruRU', '[UNUSED] Rabid Johnny Whipple', NULL, NULL, NULL),
(614, 'ruRU', '[UNUSED] Rabid Grandpa Whipple', NULL, NULL, NULL),
(615, 'ruRU', 'Следопыт из клана Черной горы', NULL, NULL, NULL),
(616, 'ruRU', 'Трещунья', NULL, NULL, NULL),
(619, 'ruRU', 'Кудесник из Братства Справедливости', NULL, NULL, NULL),
(620, 'ruRU', 'Курица', NULL, NULL, NULL),
(621, 'ruRU', 'NPC MoP', NULL, NULL, NULL),
(622, 'ruRU', 'Гоблин-инженер', NULL, NULL, NULL),
(623, 'ruRU', 'Скелет-шахтер', NULL, NULL, NULL),
(624, 'ruRU', 'Нежить-землечерп', NULL, NULL, NULL),
(625, 'ruRU', 'Нежить-подрывник', NULL, NULL, NULL),
(626, 'ruRU', 'Штейгер Крапивец', NULL, NULL, NULL),
(628, 'ruRU', 'Черный опустошитель', NULL, NULL, NULL),
(631, 'ruRU', 'pnagle''s test dude', NULL, NULL, NULL),
(633, 'ruRU', 'Илана Карвин', NULL, NULL, NULL),
(634, 'ruRU', 'Надзиратель из Братства Справедливости', NULL, NULL, NULL),
(636, 'ruRU', 'Черный страж из Братства Справедливости', NULL, NULL, NULL),
(638, 'ruRU', 'Гоблин-наемник', NULL, NULL, NULL),
(639, 'ruRU', 'Эдвин ван Клиф', NULL, 'Главарь Братства Справедливости', NULL),
(641, 'ruRU', 'Гоблин-древоруб', NULL, NULL, NULL),
(642, 'ruRU', 'Крошшер Снида', NULL, 'Начальник лесозаготовки', NULL),
(643, 'ruRU', 'Снид', NULL, 'Начальник лесозаготовки', NULL),
(644, 'ruRU', 'Рак''Зор', NULL, 'Штейгер', NULL),
(645, 'ruRU', 'Пирожок', NULL, 'Корабельный кок', NULL),
(646, 'ruRU', 'Мистер Каюк', NULL, 'Первый помощник капитана', NULL),
(647, 'ruRU', 'Капитан Зеленямс', NULL, NULL, NULL),
(648, 'ruRU', 'Мостостроитель Трент', NULL, NULL, NULL),
(649, 'ruRU', 'Мостостроитель Дмитрий', NULL, NULL, NULL),
(650, 'ruRU', 'Мостостроитель Джесс', NULL, NULL, NULL),
(651, 'ruRU', 'Мостостроитель Даниэль', NULL, NULL, NULL),
(652, 'ruRU', 'Мостостроитель Мэттью', NULL, NULL, NULL),
(653, 'ruRU', 'Мостостроитель Алекс', NULL, NULL, NULL),
(656, 'ruRU', 'Вилдер Крапивец', NULL, NULL, NULL),
(657, 'ruRU', 'Пират из Братства Справедливости', NULL, NULL, NULL),
(658, 'ruRU', 'Стен Крепкорук', NULL, NULL, NULL),
(659, 'ruRU', 'Бройлеро гиганто', NULL, 'Черный бройлер смерти', NULL),
(660, 'ruRU', 'Знахарь из племени Кровавого Скальпа', NULL, NULL, NULL),
(661, 'ruRU', 'Джонатан Карвин', NULL, NULL, NULL),
(663, 'ruRU', 'Калор', NULL, NULL, NULL),
(664, 'ruRU', 'Бенджамин Карвин', NULL, NULL, NULL),
(667, 'ruRU', 'Воин из племени Дробителей Черепов', NULL, NULL, NULL),
(669, 'ruRU', 'Охотник из племени Дробителей Черепов', NULL, NULL, NULL),
(670, 'ruRU', 'Знахарь из племени Дробителей Черепов', NULL, NULL, NULL),
(671, 'ruRU', 'Охотник за головами из племени Кровавого Скальпа', NULL, NULL, NULL),
(672, 'ruRU', 'Духолов из племени Дробителей Черепов', NULL, NULL, NULL),
(674, 'ruRU', 'Горнорабочий Торговой Компании', NULL, NULL, NULL),
(675, 'ruRU', 'Штейгер Торговой Компании', NULL, NULL, NULL),
(676, 'ruRU', 'Геодезист Торговой Компании', NULL, NULL, NULL),
(677, 'ruRU', 'Ремонтник Торговой Компании', NULL, NULL, NULL),
(678, 'ruRU', 'Изверг из клана Мош''Огг', NULL, NULL, NULL),
(679, 'ruRU', 'Шаман из клана Мош''Огг', NULL, NULL, NULL),
(680, 'ruRU', 'Вождь Мош''Огг', NULL, NULL, NULL),
(681, 'ruRU', 'Молодой тигр Тернистой долины', NULL, NULL, NULL),
(682, 'ruRU', 'Тигр Тернистой долины', NULL, NULL, NULL),
(683, 'ruRU', 'Молодая пантера', NULL, NULL, NULL),
(684, 'ruRU', 'Тенебрюхая пантера', NULL, NULL, NULL),
(685, 'ruRU', 'Ящер Тернистой долины', NULL, NULL, NULL),
(686, 'ruRU', 'Ящер-кнутохвост', NULL, NULL, NULL),
(687, 'ruRU', 'Хищник джунглей', NULL, NULL, NULL),
(688, 'ruRU', 'Камнезобый василиск', NULL, NULL, NULL),
(689, 'ruRU', 'Хрустальный василиск', NULL, NULL, NULL),
(690, 'ruRU', 'Ледоглазый василиск', NULL, NULL, NULL),
(691, 'ruRU', 'Малый элементаль воды', NULL, NULL, NULL),
(693, 'ruRU', 'Учитель вторичных умений', NULL, 'Учитель', NULL),
(694, 'ruRU', 'Метатель топоров из племени Кровавого Скальпа', NULL, NULL, NULL),
(696, 'ruRU', 'Метатель топоров из племени Дробителей Черепов', NULL, NULL, NULL),
(697, 'ruRU', 'Шаман из племени Кровавого Скальпа', NULL, NULL, NULL),
(698, 'ruRU', 'Тигр племени Кровавого Скальпа', NULL, NULL, NULL),
(699, 'ruRU', 'Повелитель зверей из племени Кровавого Скальпа', NULL, NULL, NULL),
(700, 'ruRU', 'Пантера из племени Кровавого Скальпа', NULL, NULL, NULL),
(701, 'ruRU', 'Мистик из племени Кровавого Скальпа', NULL, NULL, NULL),
(702, 'ruRU', 'Падальщик из племени Кровавого Скальпа', NULL, NULL, NULL),
(703, 'ruRU', 'Генерал Фангор', NULL, NULL, NULL),
(704, 'ruRU', 'Косматый лесной волк', NULL, NULL, NULL),
(705, 'ruRU', 'Косматый молодой волк', NULL, NULL, NULL),
(706, 'ruRU', 'Молодой тролль из племени Мерзлогривов', NULL, NULL, NULL),
(707, 'ruRU', 'Трогг из племени Каменной Челюсти', NULL, NULL, NULL),
(708, 'ruRU', 'Малый скальный вепрь', NULL, NULL, NULL),
(709, 'ruRU', 'Солдат-наемник из клана Мош''Огг', NULL, NULL, NULL),
(710, 'ruRU', 'Чаротвор Мош''Огг', NULL, NULL, NULL),
(711, 'ruRU', 'Ардо Грязнолап', NULL, NULL, NULL),
(712, 'ruRU', 'Твердозуб из стаи Красногорья', NULL, NULL, NULL);

-- Всего записей для вставки: 299

