-- SQL запрос для вставки данных в creature_template_wdb_locale
-- Сгенерировано из Wowhead парсера
-- Локаль: ruRU
-- Записей в файле: 100

-- Удаляем существующие записи для всех ID из этого файла
DELETE FROM `creature_template_wdb_locale` WHERE `Locale` = 'ruRU' AND `ID` IN (
    713,714,715,716,717,718,723,724,725,727,728,729,730,731,732,
    733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,
    749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,
    764,765,766,767,768,769,770,771,772,773,775,777,780,781,782,
    783,784,785,786,787,789,790,791,793,794,795,796,797,798,799,
    800,801,802,804,805,806,807,808,809,810,811,812,813,814,815,
    818,819,820,821,822,823,824,826,827,828
);

-- Вставляем новые записи
INSERT INTO `creature_template_wdb_locale` (`ID`, `Locale`, `Name1`, `NameAlt1`, `Title`, `TitleAlt`) VALUES
(713, 'ruRU', 'Балир Морозный Молот', NULL, NULL, NULL),
(714, 'ruRU', 'Талин Остроглаз', NULL, NULL, NULL),
(715, 'ruRU', 'Хеминг Эрнестуэй-младший', NULL, NULL, NULL),
(716, 'ruRU', 'Барнил Каменный Горшок', NULL, NULL, NULL),
(717, 'ruRU', 'Аджек Руак', NULL, NULL, NULL),
(718, 'ruRU', 'Сэр С. Дж. Эрлджедин', NULL, NULL, NULL),
(723, 'ruRU', 'Палач Мош''Огг', NULL, NULL, NULL),
(724, 'ruRU', 'Сильный трогг из племени Каменной Челюсти', NULL, NULL, NULL),
(725, 'ruRU', '[UNUSED] Skeletal Enforcer', NULL, NULL, NULL),
(727, 'ruRU', 'Стальгорнский горный пехотинец', NULL, NULL, NULL),
(728, 'ruRU', 'Баг''тира', NULL, NULL, NULL),
(729, 'ruRU', 'Син''Далл', NULL, NULL, NULL),
(730, 'ruRU', 'Тетис', NULL, NULL, NULL),
(731, 'ruRU', 'Король Бангалаш', NULL, NULL, NULL),
(732, 'ruRU', 'Мурлок-скрытень', NULL, NULL, NULL),
(733, 'ruRU', 'Сержант Йохва', NULL, NULL, NULL),
(734, 'ruRU', 'Капрал Блуф', NULL, 'Торговец', NULL),
(735, 'ruRU', 'Речной мурлок-бегун', NULL, NULL, NULL),
(736, 'ruRU', 'Пантера', NULL, NULL, NULL),
(737, 'ruRU', 'Кебок', NULL, NULL, NULL),
(738, 'ruRU', 'Рядовой Торсен', NULL, NULL, NULL),
(739, 'ruRU', 'Брат Нимез', NULL, NULL, NULL),
(740, 'ruRU', 'Юный дракончик', NULL, NULL, NULL),
(741, 'ruRU', 'Мечтательный дракончик', NULL, NULL, NULL),
(742, 'ruRU', 'Зеленая драконида', NULL, NULL, NULL),
(743, 'ruRU', 'Драконида-сновидица', NULL, NULL, NULL),
(744, 'ruRU', 'Зеленый чешуйчатый губитель', NULL, NULL, NULL),
(745, 'ruRU', 'Капитан чешуйчатых губителей', NULL, NULL, NULL),
(746, 'ruRU', 'Старый драконор', NULL, NULL, NULL),
(747, 'ruRU', 'Болотный мурлок', NULL, NULL, NULL),
(749, 'ruRU', 'Болотный темножитель', NULL, NULL, NULL),
(750, 'ruRU', 'Болотный чернильщик', NULL, NULL, NULL),
(751, 'ruRU', 'Болотный трупоед', NULL, NULL, NULL),
(752, 'ruRU', 'Болотный оракул', NULL, NULL, NULL),
(753, 'ruRU', '[UNUSED] Rebel Soldier', NULL, NULL, NULL),
(754, 'ruRU', 'Дозорный лагеря повстанцев', NULL, NULL, NULL),
(755, 'ruRU', 'Грязелюб из племени Заблудших', NULL, NULL, NULL),
(756, 'ruRU', 'Пантера племени Дробителей Черепов', NULL, NULL, NULL),
(757, 'ruRU', 'Рыбак из племени Заблудших', NULL, NULL, NULL),
(758, 'ruRU', 'Тигр племени Дробителей Черепов', NULL, NULL, NULL),
(759, 'ruRU', 'Охотник из племени Заблудших', NULL, NULL, NULL),
(760, 'ruRU', 'Грязекоп из племени Заблудших', NULL, NULL, NULL),
(761, 'ruRU', 'Ясновидец из племени Заблудших', NULL, NULL, NULL),
(762, 'ruRU', 'Заблудший искатель разрыва', NULL, NULL, NULL),
(763, 'ruRU', 'Вождь из племени Заблудших', NULL, NULL, NULL),
(764, 'ruRU', 'Тиноброд', NULL, NULL, NULL),
(765, 'ruRU', 'Старый тиноброд', NULL, NULL, NULL),
(766, 'ruRU', 'Перевитый ужас', NULL, NULL, NULL),
(767, 'ruRU', 'Болотный ягуар', NULL, NULL, NULL),
(768, 'ruRU', 'Пантера Тени', NULL, NULL, NULL),
(769, 'ruRU', 'Смертоносный тарантул', NULL, NULL, NULL),
(770, 'ruRU', 'Капрал Калеб', NULL, NULL, NULL),
(771, 'ruRU', 'Командор Сквернстром', NULL, NULL, NULL),
(772, 'ruRU', 'Тигрица Тернистой долины', NULL, NULL, NULL),
(773, 'ruRU', 'Кразек', NULL, NULL, NULL),
(775, 'ruRU', 'Посланник Курцена', NULL, NULL, NULL),
(777, 'ruRU', 'Эми Дэвенпорт', NULL, 'Торговка', NULL),
(780, 'ruRU', 'Мистик из племени Дробителей Черепов', NULL, NULL, NULL),
(781, 'ruRU', 'Охотник за головами из племени Дробителей Черепов', NULL, NULL, NULL),
(782, 'ruRU', 'Разведчик из племени Дробителей Черепов', NULL, NULL, NULL),
(783, 'ruRU', 'Берсерк из племени Дробителей Черепов', NULL, NULL, NULL),
(784, 'ruRU', 'Повелитель зверей из племени Дробителей Черепов', NULL, NULL, NULL),
(785, 'ruRU', 'Скелет-хранитель', NULL, NULL, NULL),
(786, 'ruRU', 'Грелин Белобород', NULL, NULL, NULL),
(787, 'ruRU', 'Скелет-лекарь', NULL, NULL, NULL),
(789, 'ruRU', 'Кимберли Хайетт', NULL, 'Торговец луками', NULL),
(790, 'ruRU', 'Карен Тейлор', NULL, 'Товары для кузнецов и горняков', NULL),
(791, 'ruRU', 'Линдси Ашлок', NULL, 'Сто мелочей', NULL),
(793, 'ruRU', 'Кара Адамс', NULL, 'Щитник', NULL),
(794, 'ruRU', 'Мэтт', NULL, NULL, NULL),
(795, 'ruRU', 'Марк', NULL, NULL, NULL),
(796, 'ruRU', 'Джошуа', NULL, NULL, NULL),
(797, 'ruRU', 'Бо', NULL, NULL, NULL),
(798, 'ruRU', 'Соломон', NULL, NULL, NULL),
(799, 'ruRU', 'Кевин', NULL, NULL, NULL),
(800, 'ruRU', 'Кайл', NULL, NULL, NULL),
(801, 'ruRU', 'Эрик', NULL, NULL, NULL),
(802, 'ruRU', 'Джей', NULL, NULL, NULL),
(804, 'ruRU', 'Дана', NULL, NULL, NULL),
(805, 'ruRU', 'Камерон', NULL, NULL, NULL),
(806, 'ruRU', 'Джон', NULL, NULL, NULL),
(807, 'ruRU', 'Лиза', NULL, NULL, NULL),
(808, 'ruRU', 'Грик''нир Холодный', NULL, NULL, NULL),
(809, 'ruRU', '[UNUSED] Smith Theo', NULL, 'Торговец оружием', NULL),
(810, 'ruRU', 'Аарон', NULL, NULL, NULL),
(811, 'ruRU', 'Хосе', NULL, NULL, NULL),
(812, 'ruRU', 'Альма Жанруза', NULL, 'Учительница травничества', NULL),
(813, 'ruRU', 'Полковник Курцен', NULL, NULL, NULL),
(814, 'ruRU', 'Сержант Малтус', NULL, NULL, NULL),
(815, 'ruRU', 'Букмекер Ирод', NULL, NULL, NULL),
(818, 'ruRU', 'Май''Зот', NULL, NULL, NULL),
(819, 'ruRU', 'Слуга Илгалара', NULL, NULL, NULL),
(820, 'ruRU', 'Разведчица Риэла', NULL, 'Дружина Западного края', NULL),
(821, 'ruRU', 'Капитан Данувин', NULL, 'Дружина Западного края', NULL),
(822, 'ruRU', 'Молодой лесной медведь', NULL, NULL, NULL),
(823, 'ruRU', 'Сержант Виллем', NULL, NULL, NULL),
(824, 'ruRU', 'Землекоп из Братства Справедливости', NULL, NULL, NULL),
(826, 'ruRU', 'Дозорный Жан', NULL, 'Ночной Дозор', NULL),
(827, 'ruRU', 'Дозорный Мокарски', NULL, 'Ночной Дозор', NULL),
(828, 'ruRU', 'Дозорный Петрас', NULL, 'Ночной Дозор', NULL);

-- Всего записей в файле: 100
